---
### YAML section (use # for comments)
title: "Expression specificity plots"
author: "Pascal N. Timshel, Pers Lab"
date: "`r Sys.time()`" # Sys.Date()
output:
  html_notebook: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
  html_document:
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---


```{r}
### Extract the code from the notebook
# knitr::purl("nb-template.Rmd", output = "output_code_blocks_extracted.R", documentation = 1)
```


# Setup

```{r, message = FALSE, results='hide', warning=FALSE}
library(tidyverse)
library(here)

library(gghighlight)
```


# Notebook specific parameters
```{r}
setwd(here("src/expression_specificity"))
```

```{r}
########################################################################################################################
################################################## Tabula Muris ############################################################
########################################################################################################################
```



```{r}
########################################################################################################################
################################################## MOUSEBRAIN ############################################################
########################################################################################################################
```


# Load mousebrain SEM_obs
```{r}
load("/raid5/projects/timshel/sc-genetics/sc-genetics/src/GE-mousebrain/mousebrain.sem_obj.RData")
```

```{r}
df.es <- sem_obj$sem_meta$mean %>% mutate(gene=sem_obj$genes) %>% select(gene, everything())
head(df.es)
```

# Genes
AGRP ENSG00000159723
DRD2 ENSG00000149295 | MSN1, MSN5, MSN6 ns.
DRD1 ENSG00000184845
POMC ENSG00000115138


```{r}
gene.selected <- "ENSG00000149295" # DRD2
gene.selected <- "ENSG00000184845" # DRD1
gene.selected <- "ENSG00000159723" # AGRP
df.plot <- df.es %>% filter(gene==gene.selected) %>% select(-gene) %>% gather()
# ggplot(df.plot, aes(key))
df.plot %>% arrange(desc(value))

# DEINH6	Arcuate hypothalamic nucleus (probably, Npy, Agrp cells)
```




