
# Load data 
```{r}
# Mouse brain
kMEs <- read.csv(gzfile("/raid5/projects/timshel/sc-genetics/sc-genetics/out/module_correlation_graph/mousebrain.all_modules_kME.csv.gz"))


# Tabula muris
kMEs <- read.csv(gzfile("/projects/timshel/sc-genetics/sc-genetics/out/module_correlation_graph/tabula_muris.all_modules_kME.csv.gz"))

kMEs
rownames(kMEs) <- kMEs[, 1]
kMEs <- kMEs[, -1]


# Mouse brain
meta <- read.csv("/raid5/projects/timshel/sc-genetics/sc-genetics/out/module_correlation_graph/mousebrain.module_prioritization.ldsc.metadata.MULTI_TRAIT.csv")


# Tabula muris
meta <- read.csv("/raid5/projects/timshel/sc-genetics/sc-genetics/out/module_correlation_graph/tabula_muris.module_prioritization.ldsc.metadata.MULTI_TRAIT.csv")


```


```{r}
correlation <- data.frame(matrix(NA, nrow = 100, ncol = 100))


meta.BMI <- meta[which(meta$gwas == "BMI_Yengo2018"), ]

idx <- order(meta.BMI$module_ldsc_pval, decreasing = F)[1:100]

# Mouae brain
#meta.tophundred <- meta.BMI[idx, c("module_id", "module_origin", "module_ldsc_pval")]

# Tabula muris
meta.tophundred <- meta.BMI[idx, c("module_id", "module_origin", "module_ldsc_pval", "tissue")]


# Mouse brain
#meta.tophundred$module_id_updated <- paste(meta.tophundred$module_origin, gsub("^.*\\.", "", meta.tophundred$module_id), sep = ".")
#meta.BMI

# Tabula muris
meta.tophundred$module_id_updated <- meta.tophundred$module_id


colnames(correlation) <- meta.tophundred$module_id_updated
rownames(correlation) <- make.names(colnames(correlation), unique=TRUE)
correlation

m <- 1

for (i in 1:ncol(correlation)) {

  for (j in 1:ncol(correlation)) {

    genes.idx.module.i <- which(!is.na(kMEs[, colnames(correlation)[i]]))
    genes.idx.module.j <- which(!is.na(kMEs[, colnames(correlation)[j]]))
    genes.idx.intersect <- intersect(genes.idx.module.i, genes.idx.module.j)

    correlation[i, j] <- cor(kMEs[genes.idx.intersect, colnames(correlation)[i]], kMEs[genes.idx.intersect, colnames(correlation)[j]])

  }
}  


correlation.MACA <- correlation
correlation.MACA
```


```{r}
library(igraph)
library(dplyr)
library(reshape2)

cor.matrix <- as.matrix(correlation.MACA)
cor.matrix
# Replace upper triangle of the matrix with number that can be used for filtering
cor.matrix[upper.tri(cor.matrix)] <- 2
 
cor.df <- melt(cor.matrix)
# Filter out the upper matrix values
# Filter out the self correlations

names(cor.df) <- c('from', 'to', 'weight')
cor.df <- filter(cor.df, weight != 2) %>% filter(from != to)

cor.df$weight[cor.df$weight < 0.5] <- 0

# Create igraph S3 object
net <- graph.data.frame(cor.df, directed = FALSE)
# Store original margins
orig.mar <- par()$mar
 
# Set new margins to limit whitespace in plot
par(mar=rep(.1, 4))

# not much difference in the edge width given the values
# but I included it for reference's sake
net2 <- delete_edges(net, E(net)[weight < 0.5])
ceb <- cluster_edge_betweenness(net2)
cor.df
Q.values <- meta.tophundred$module_ldsc_pval

idx <- match(names(net2[1]), meta.tophundred$module_id_updated)
size <- -log10(Q.values)[idx]


```



# Cell type mouse brain
```{r}
table(gsub("\\.(.*)", "", meta$module_id))

cell.types <- vector(length = nrow(correlation))

cell.types[which(grepl("Neurons", meta.tophundred$module_id))] <- "hotpink1"
cell.types[which(grepl("Ependymal", meta.tophundred$module_id))] <- "olivedrab3"
cell.types[which(grepl("Oligos", meta.tophundred$module_id))] <- "turquoise3"
cell.types[which(grepl("PeripheralGlia", meta.tophundred$module_id))] <- "orange2"
cell.types[which(grepl("Immune", meta.tophundred$module_id))] <- "forestgreen"
cell.types[which(grepl("Astrocytes", meta.tophundred$module_id))] <- "deeppink4"
cell.types[which(grepl("Vascular", meta.tophundred$module_id))] <- "navyblue"
idx <- match(names(net2[1]), meta.tophundred$module_id_updated)

cell.types <- cell.types[idx]
```

# Tissue tabula muris
```{r}
table(meta.tophundred$tissue)

cell.types <- vector(length = nrow(correlation))

cell.types[which(grepl("Aorta", meta.tophundred$tissue))] <- "hotpink1"
cell.types[which(grepl("Bladder", meta.tophundred$tissue))] <- "olivedrab3"
cell.types[which(grepl("Brain", meta.tophundred$tissue))] <- "red"
cell.types[which(grepl("Colon", meta.tophundred$tissue))] <- "turquoise3"
cell.types[which(grepl("Diaphragm", meta.tophundred$tissue))] <- "orange2"
cell.types[which(grepl("Fat", meta.tophundred$tissue))] <- "forestgreen"
cell.types[which(grepl("Heart", meta.tophundred$tissue))] <- "deeppink4"
cell.types[which(grepl("Kidney", meta.tophundred$tissue))] <- "navyblue"

cell.types[which(grepl("Liver", meta.tophundred$tissue))] <- "hotpink3"
cell.types[which(grepl("Lung", meta.tophundred$tissue))] <- "black"
cell.types[which(grepl("Mammary", meta.tophundred$tissue))] <- "turquoise"
cell.types[which(grepl("Marrow", meta.tophundred$tissue))] <- "orange"
cell.types[which(grepl("Muscle", meta.tophundred$tissue))] <- "green"
cell.types[which(grepl("Pancreas", meta.tophundred$tissue))] <- "white"
cell.types[which(grepl("Skin", meta.tophundred$tissue))] <- "blue"
cell.types[which(grepl("Spleen", meta.tophundred$tissue))] <- "grey"
cell.types[which(grepl("Thymus", meta.tophundred$tissue))] <- "yellow"



idx <- match(names(net2[1]), meta.tophundred$module_id_updated)

cell.types <- cell.types[idx]
meta.tophundred
```


```{r}
#pdf("Network_MACA.pdf", width = 10, height=5)

set.seed(10)

par(oma=c(0,0,0,0), mar=c(0,0,0,0))
size2 <- log10(size) 
plot(net2, layout = layout.fruchterman.reingold(net2), asp = 1, edge.width = E(net2)$weight*4, vertex.label =  "",
     vertex.color = adjustcolor(cell.types, alpha.f = 0.9), 
     vertex.size = size2 * 12, vertex.frame.width = 2)


# Legend
sizeCut<- c(18, 10, 2)
sizeCutScale <- log(sizeCut) * 5
legend1 <- legend(-1.7, 1, legend = unique(sizeCut), pt.cex = sizeCutScale/200,
            pch=NA, pt.bg = 'white', box.col = "white", title = expression(-log[10](Q)), title.adj = 0, y.intersp = 1.5)
x <- (legend1$text$x + legend1$rect$left) / 2
y <- legend1$text$y
symbols(x, y, circles = sizeCutScale/200, inches=FALSE, add = TRUE, bg = "grey")


legend2 <- legend(1.2, 1, legend = c("Astrocytes", "Glia (peri)", "Ependymal", "Microglia",
                                            "Neurons", "Oligos", "OPCs"), pt.cex=sizeCutScale/200, 
            pch=21, pt.bg = 'white', box.col = "white", title = "Cell type", title.adj = 0, y.intersp = 1.3)
q <- (legend2$text$x + legend2$rect$left) / 2
p <- legend2$text$y
symbols(q, p, circles = rep(0.05, 7), inches=FALSE, add = TRUE, bg = c("deeppink4", "orange2", "olivedrab3", "forestgreen", "hotpink1",
        "turquoise3", "navyblue"))

```

# Tabula muris
```{r}
#pdf("Network_MACA.pdf", width = 10, height=5)

set.seed(10)

par(oma=c(0,0,0,0), mar=c(0,0,0,0))
size2 <- log10(size) 
plot(net2, layout = layout.fruchterman.reingold(net2), asp = 1, edge.width = E(net2)$weight*4, vertex.label =  "",
     vertex.color = adjustcolor(cell.types, alpha.f = 0.9), 
     vertex.size = size2 * 22, vertex.frame.width = 2)


# Legend
legend2 <- legend(1.2, 1, legend = names(table(meta.tophundred$tissue))[-c(18, 19)]
, pt.cex=sizeCutScale/200, 
            pch=21, pt.bg = 'white', box.col = "white", title = "Tissue", title.adj = 0, y.intersp = 1.3)
q <- (legend2$text$x + legend2$rect$left) / 2
p <- legend2$text$y
symbols(q, p, circles = rep(0.05, 17), inches=FALSE, add = TRUE, bg = c("hotpink1", "orange2", "olivedrab3", "red", "forestgreen", "deeppink4", "turquoise3", "navyblue", "hotpink3", "black", "turquoise", "orange", "green", "white", "blue", "grey", "yellow"))
```

