---
### YAML section (use # for comments)
title: "SEM models heatmap"
author: "Pascal N. Timshel, Pers Lab"
date: "`r Sys.time()`" # Sys.Date()
output:
  html_notebook: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
  html_document:
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---


```{r, results='hide'}
library(tidyverse)
# library(superheat) # https://rlbarter.github.io/superheat/basic-usage.html
# library(pheatmap) # https://davetang.org/muse/2018/05/15/making-a-heatmap-in-r-with-the-pheatmap-package/
# library(d3heatmap) # interactive, https://cran.r-project.org/web/packages/d3heatmap/vignettes/Introduction.html
library(heatmaply) # https://github.com/talgalili/heatmaply | Install this lib before you can save figs --> webshot::install_phantomjs()

```

```{r}
wd <- "/raid5/projects/timshel/sc-genetics/sc-genetics/src/GE-mousebrain/"
setwd(wd)
```


# Load data
```{r}
load(file="mousebrain.sem_obj.RData") # human
```


```{r}
sem_obj[["sem_meta"]][["median"]] %>% slice(1:100)
```

```{r}
sem_obj[["group_by_annotation.sem_bin"]][[1]] %>% head()
```


# Median heatmap

```{r}
df.plot <- sem_obj[["sem_meta"]][["sd"]] %>% 
  mutate(gene=sem_obj[["genes"]]) %>% 
  slice(1:10) %>%
  column_to_rownames(var="gene") %>% as.data.frame() # this step must come last to keep the rownames.
print(class(df.plot))
df.plot %>% head()
```


```{r, fig.width=12, fig.height=10}
heatmaply(df.plot)
```