
import os
import sys
import time
import glob

import subprocess


###################################### USAGE ######################################

# time python2 wrapper_run_cmd.py |& tee wrapper_run_cmd.out.txt

###################################### XXX ######################################

# ### BMI
# list_cmds = ["Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/body_BMI_Locke2015.gwassumstats.rolypoly_fmt.tab.gz --gwas_name body_BMI_Locke2015 --run_name gene.10kb.squared.protein_coding_only --window_position gene --window_size_kb 10 --pos_transformation square --protein_coding_only --n_cores 10 &> log.body_BMI_Locke2015-gene.10kb.squared.protein_coding_only.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/body_BMI_Locke2015.gwassumstats.rolypoly_fmt.tab.gz --gwas_name body_BMI_Locke2015 --run_name gene.10kb.squared.all_genes --window_position gene --window_size_kb 10 --pos_transformation square --n_cores 10 &> log.body_BMI_Locke2015-gene.10kb.squared.all_genes.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/body_BMI_Locke2015.gwassumstats.rolypoly_fmt.tab.gz --gwas_name body_BMI_Locke2015 --run_name tss.10kb.squared.all_genes --window_position tss --window_size_kb 10 --pos_transformation square --n_cores 10 &> log.body_BMI_Locke2015-tss.10kb.squared.all_genes.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/body_BMI_Locke2015.gwassumstats.rolypoly_fmt.tab.gz --gwas_name body_BMI_Locke2015 --run_name tss.20kb.squared.all_genes --window_position tss --window_size_kb 20 --pos_transformation square --n_cores 10 &> log.body_BMI_Locke2015-tss.20kb.squared.all_genes.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/body_BMI_Locke2015.gwassumstats.rolypoly_fmt.tab.gz --gwas_name body_BMI_Locke2015 --run_name tss.10kb.pos_only.all_genes --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 10 &> log.body_BMI_Locke2015-tss.10kb.pos_only.all_genes.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/body_BMI_Locke2015.gwassumstats.rolypoly_fmt.tab.gz --gwas_name body_BMI_Locke2015 --run_name tss.10kb.abs.all_genes --window_position tss --window_size_kb 10 --pos_transformation abs --n_cores 10 &> log.body_BMI_Locke2015-tss.10kb.abs.all_genes.out.txt"
# ]

# ### SCZ
# list_cmds = ["Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/mental_SCZ_Ripke2014.gwassumstats.rolypoly_fmt.tab.gz --gwas_name mental_SCZ_Ripke2014 --run_name gene.10kb.squared.protein_coding_only --window_position gene --window_size_kb 10 --pos_transformation square --protein_coding_only --n_cores 15 &> log.mental_SCZ_Ripke2014-gene.10kb.squared.protein_coding_only.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/mental_SCZ_Ripke2014.gwassumstats.rolypoly_fmt.tab.gz --gwas_name mental_SCZ_Ripke2014 --run_name gene.10kb.squared.all_genes --window_position gene --window_size_kb 10 --pos_transformation square --n_cores 15 &> log.mental_SCZ_Ripke2014-gene.10kb.squared.all_genes.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/mental_SCZ_Ripke2014.gwassumstats.rolypoly_fmt.tab.gz --gwas_name mental_SCZ_Ripke2014 --run_name tss.10kb.squared.all_genes --window_position tss --window_size_kb 10 --pos_transformation square --n_cores 15 &> log.mental_SCZ_Ripke2014-tss.10kb.squared.all_genes.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/mental_SCZ_Ripke2014.gwassumstats.rolypoly_fmt.tab.gz --gwas_name mental_SCZ_Ripke2014 --run_name tss.20kb.squared.all_genes --window_position tss --window_size_kb 20 --pos_transformation square --n_cores 15 &> log.mental_SCZ_Ripke2014-tss.20kb.squared.all_genes.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/mental_SCZ_Ripke2014.gwassumstats.rolypoly_fmt.tab.gz --gwas_name mental_SCZ_Ripke2014 --run_name tss.10kb.pos_only.all_genes --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 15 &> log.mental_SCZ_Ripke2014-tss.10kb.pos_only.all_genes.out.txt",
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/mental_SCZ_Ripke2014.gwassumstats.rolypoly_fmt.tab.gz --gwas_name mental_SCZ_Ripke2014 --run_name tss.10kb.abs.all_genes --window_position tss --window_size_kb 10 --pos_transformation abs --n_cores 15 &> log.mental_SCZ_Ripke2014-tss.10kb.abs.all_genes.out.txt"
# ]

### [*COMPLETE*] MISC traits (almost all pos_only) 
# list_cmds = [
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation none --n_cores 10 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Locke2015", run_name="tss.10kb.none.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 10 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Locke2015", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 10 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_SCZ_Ripke2014", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 10 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_T2D", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 10 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_WHR_Shungin2015", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 10 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="lipids_TC_Willer2013_Willer2013", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 10 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="blood_EOSINOPHIL_COUNT", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/body_BMI_Locke2015.gwassumstats.rolypoly_fmt.tab.gz --gwas_name body_BMI_Locke2015 --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 100 --pos_transformation pos_only --n_cores 10 &> log.body_BMI_Locke2015-{run_name}.out.txt".format(run_name="tss.100kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/body_BMI_Locke2015.gwassumstats.rolypoly_fmt.tab.gz --gwas_name body_BMI_Locke2015 --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 500 --pos_transformation pos_only --n_cores 10 &> log.body_BMI_Locke2015-{run_name}.out.txt".format(run_name="tss.500kb.pos_only.all_genes")
# ]

## [*COMPLETE*] NEW GWAS traits + running v2.1 (without changes to the SNP model)
# list_cmds = [
# "Rscript run_rolypoly_multi_expr_datasets-v2.1_only_gwas_link.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Yengo2018", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.1_only_gwas_link.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="cov_EduYears_Lee2018", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.1_only_gwas_link.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_T2D_Guarch2018", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.1_only_gwas_link.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_height_Yengo2018", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v2.1_only_gwas_link.R --gwas_file /raid5/projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v2.pos_only --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_AN_Boraska2014", run_name="tss.10kb.pos_only.all_genes")
# ]

### Testing NEW gwas traits: running v3 UNIVARIATE (without changes to the SNP model)
# *OBS* unsing --gwas_linked_file and not --gwas_file
# list_cmds = [
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2.pos_only/rolypoly_objs.{gwas_name}.tss.10kb.pos_only.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core1.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Yengo2018", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2.pos_only/rolypoly_objs.{gwas_name}.tss.10kb.pos_only.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core1.txt --window_position tss --window_size_kb 10 --pos_transformation square --n_bootstrap 100 --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Yengo2018", run_name="tss.10kb.square.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2.pos_only/rolypoly_objs.{gwas_name}.tss.10kb.pos_only.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core1.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_height_Yengo2018", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2.pos_only/rolypoly_objs.{gwas_name}.tss.10kb.pos_only.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core1.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="cov_EduYears_Lee2018", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2.pos_only/rolypoly_objs.{gwas_name}.tss.10kb.pos_only.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core1.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_T2D_Guarch2018", run_name="tss.10kb.pos_only.all_genes"),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir /raid5/projects/timshel/sc-genetics/sc-genetics/src/RP-meta/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2.pos_only/rolypoly_objs.{gwas_name}.tss.10kb.pos_only.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core1.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores 25 &> log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_AN_Boraska2014", run_name="tss.10kb.pos_only.all_genes")
# ]


###################################### MANY GWAS: running v3 UNIVARIATE ######################################
### running v3 UNIVARIATE (without changes to the SNP model)
### *OBS* unsing --gwas_linked_file and not --gwas_file
# 3/4 GWAS jobs with 10 cores each results in avg. load of 330%
########### N_CORES=3
########### OUTDIR = "/scratch/sc-genetics"
########### if not os.path.exists(OUTDIR): # need to make it for the log files to go the same place.
########### 	os.makedirs(OUTDIR)
########### list_cmds = [
########### ### BMI (mix new + old)
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Yengo2018", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation square --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Yengo2018", run_name="tss.10kb.square.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation none --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Yengo2018", run_name="tss.10kb.none.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Locke2015_EUR", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # ### Core GWAS - old
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_WHR_Shungin2015", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_SCZ_Ripke2014", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # ### Core GWAS - new
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_height_Yengo2018", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_AN_Boraska2014", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="cov_EduYears_Lee2018", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_T2D_Guarch2018", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # ### Core GWAS - old
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="lipids_TC", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### ### Old GWAS (different DIR for gwas_linked_file)
########### "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMIz", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_HEIGHTz", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_WHRadjBMIz", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="cov_EDU_COLLEGE", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="cov_EDU_YEARS", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_T2D", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="lipids_HDL", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="lipids_LDL", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="lipids_TG", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_NEUROTICISM", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="repro_MENARCHE_AGE", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="blood_EOSINOPHIL_COUNT", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="blood_HIGH_LIGHT_SCATTER_RETICULOCYTE_COUNT", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="blood_LYMPHOCYTE_COUNT", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="blood_MEAN_CORPUSCULAR_HEMOGLOBIN", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.univariate-nboot100 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="blood_MEAN_SPHERED_CELL_VOL", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
########### ]

### SCRATCH
# Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name body_BMI_Locke2015 --run_name tss.10kb.pos_only.all_genes --outdir /scratch/out.rolypoly_objs-v3.univariate-nboot500 --gwas_linked_file /raid5/projects/timshel/sc-genetics/sc-genetics/out/out.rolypoly_objs-v2/rolypoly_objs.body_BMI_Locke2015.tss.10kb.square.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.core2.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 500 --n_cores 10 &> log.body_BMI_Locke2015-tss.10kb.pos_only.all_genes.SCRATCH.out.txt


###################################### running v3 UNIVARIATE: LDSC GWAS ######################################
# ### *OBS* using --gwas_linked_file and not --gwas_file
# # 3/4 GWAS jobs with 10 cores each results in avg. load of 330%
# ### *OBS* running with --ldsc_input_mode
# N_CORES=20 # ---> ~200% CPU for LDSC jobs [10 cores gave ~30% CPU load]
# LOG_PREFIX="ldsc_gwas"
# OUTDIR = "/scratch/sc-genetics"
# if not os.path.exists(OUTDIR): # need to make it for the log files to go the same place.
# 	os.makedirs(OUTDIR)
# list_cmds = [
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Alzheimer", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Anorexia", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Autism", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Bipolar_Disorder", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="BMI1", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Celiac", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Coronary_Artery_Disease", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Crohns_Disease", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="DS", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Ever_Smoked", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Fasting_Glucose", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="HDL", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Height1", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="IBD", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="LDL", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Lupus", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Multiple_sclerosis", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Neuroticism", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Primary_biliary_cirrhosis", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Rheumatoid_Arthritis", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Schizophrenia", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="SWB", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Triglycerides", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Type_1_Diabetes", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Type_2_Diabetes", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Ulcerative_Colitis", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Years_of_Education1", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_ldsc/alkesgroup-snpsnap_mapped/{gwas_name}.gwassumstats.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.ldsc.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --ldsc_input_mode --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="Years_of_Education2", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# ]



###################################### NEW GWAS April 12th running v3 UNIVARIATE ######################################

#### NEW GWAS April 12th (n=22)
### body_HEIGHT_Wood2014
### body_WHRadjBMI_Shungin2015_EUR
### body_WHR_Shungin2015_EUR
### cov_INSOMNIA_Hammerschlag2017
### cov_INTELLIGENCE_Sniekers2017
### disease_AID_ALL
### disease_ALLERGY_ECZEMA_DIAGNOSED
### disease_ASTHMA_DIAGNOSED
### disease_CARDIOVASCULAR
### mental_AD_Lambert2013
### mental_ASD_iPSYCH_PGC_Grove2018
### mental_BIP_PGC2012
### mental_DS_Okbay2016
### mental_MDD_PGC2013
### mental_Neuroticism_Okbay2016
### mental_SWB_Okbay2016
### pigment_HAIR
### pigment_SKIN
### pigment_SUNBURN
### pigment_TANNING
### repro_MENOPAUSE_AGE
### repro_menopause_Day2015



# ### running v3 UNIVARIATE (without changes to the SNP model)
# ### *OBS* unsing --gwas_linked_file and not --gwas_file
# # 3/4 GWAS jobs with 10 cores each results in avg. load of 330%
# N_CORES=6
# OUTDIR = "/scratch/sc-genetics"
# if not os.path.exists(OUTDIR): # need to make it for the log files to go the same place.
# 	os.makedirs(OUTDIR)

# list_cmds = [
# # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_HEIGHT_Wood2014", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_WHRadjBMI_Shungin2015_EUR", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_WHR_Shungin2015_EUR", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="cov_INSOMNIA_Hammerschlag2017", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="cov_INTELLIGENCE_Sniekers2017", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# # "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_AID_ALL", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_ALLERGY_ECZEMA_DIAGNOSED", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_ASTHMA_DIAGNOSED", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_CARDIOVASCULAR", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_AD_Lambert2013", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_ASD_iPSYCH_PGC_Grove2018", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_BIP_PGC2012", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_DS_Okbay2016", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_MDD_PGC2013", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_Neuroticism_Okbay2016", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_SWB_Okbay2016", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="pigment_HAIR", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="pigment_SKIN", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="pigment_SUNBURN", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="pigment_TANNING", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="repro_MENOPAUSE_AGE", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.gwas_linking_only.INFERENCE --gwas_linked_file /scratch/sc-genetics/out.rolypoly_objs-v3.gwas_linking_only/rolypoly_objs.{gwas_name}.tss.10kb.all_genes.gwas_linked.RData --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.atlas.txt --window_position tss --window_size_kb 10 --pos_transformation pos_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{gwas_name}-{run_name}.out.txt".format(gwas_name="repro_menopause_Day2015", run_name="tss.10kb.pos_only.all_genes.nboot100", outdir=OUTDIR, n_cores=N_CORES),
# ]


###################################### running v3 UNIVARIATE: HAPMAP3 GWAS ######################################
# body_BMI_Yengo2018
# mental_SCZ_Ripke2014
# disease_T2D_Guarch2018
# cov_EduYears_Lee2018
# lipids_HDL_Willer2013
# lipids_LDL_Willer2013
# lipids_TC_Willer2013
# NULL_GWAS_1KG_phase3_EUR_N10
# NULL_GWAS_1KG_phase3_EUR_N1
# NULL_GWAS_1KG_phase3_EUR_N2
# NULL_GWAS_1KG_phase3_EUR_N3
# NULL_GWAS_1KG_phase3_EUR_N4
# NULL_GWAS_1KG_phase3_EUR_N5
# NULL_GWAS_1KG_phase3_EUR_N6
# NULL_GWAS_1KG_phase3_EUR_N7
# NULL_GWAS_1KG_phase3_EUR_N8
# NULL_GWAS_1KG_phase3_EUR_N9

# ### *OBS* running with --protein_coding_only
N_CORES=10 
	# 7 cores: moderate low CPU usage. 
	# 10 cores: ~20-30% CPU usage on average. (in peaks, it will use up to ~80%)
LOG_PREFIX="hm3_gwas"
OUTDIR = "/scratch/sc-genetics"
if not os.path.exists(OUTDIR): # need to make it for the log files to go the same place.
	os.makedirs(OUTDIR)
list_cmds_XXXXXXXXXXXX_WORKS_but_switched_temporarily_to_NOVO_BULK = [
"Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Yengo2018", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
"Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_SCZ_Ripke2014", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="disease_T2D_Guarch2018", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="cov_EduYears_Lee2018", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="lipids_HDL_Willer2013", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
"Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="lipids_LDL_Willer2013", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="lipids_TC_Willer2013", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N10", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N1", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N2", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N3", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N4", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N5", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N6", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N7", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N8", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
# "Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.mousebrain.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="NULL_GWAS_1KG_phase3_EUR_N9", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
]

list_cmds = [
"Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.novo_bulk.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="body_BMI_Yengo2018", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
"Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.novo_bulk.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="mental_SCZ_Ripke2014", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
"Rscript run_rolypoly_multi_expr_datasets-v3.R --gwas_file /projects/timshel/sc-genetics/sc-genetics/data/gwas_sumstats_hapmap3/{gwas_name}.gwassumstats.hapmap3.rolypoly_fmt.tab.gz --gwas_name {gwas_name} --run_name {run_name} --outdir {outdir}/out.rolypoly_objs-v3.hm3_protein_coding_only.univariate-nboot100 --expr_data_list /raid5/projects/timshel/sc-genetics/sc-genetics/data/list_expr_data.novo_bulk.txt --window_position tss --window_size_kb 10 --pos_transformation none --protein_coding_only --n_bootstrap 100 --n_cores {n_cores} &> {outdir}/log.{log_prefix}.{gwas_name}-{run_name}.out.txt".format(gwas_name="lipids_LDL_Willer2013", run_name="tss.10kb.hm3.none.protein_coding_only.nboot100", outdir=OUTDIR, n_cores=N_CORES, log_prefix=LOG_PREFIX),
]




# list_cmds = ["sleep 10"] * 10 # ['sleep 3', 'sleep 3', 'sleep 3']


list_of_processes = []
batch = 1
for i, cmd in enumerate(list_cmds, start=1):
    print "batch = {} | i = {} | Running command: {}".format(batch, i, cmd)
    print cmd
    p = subprocess.Popen(cmd, shell=True)
    list_of_processes.append(p)
    print "batch = {} | i = {} | list_of_processes:".format(batch, i)
    print list_of_processes
    if i % 1 == 0:
        batch += 1
        for process in list_of_processes:
            print "=========== Waiting for process: {} ===========".format(process.pid)
            process.wait()
        list_of_processes = [] # 'reset' list

### wait for the rest for the rest of the processes
print "*********** DONE IN MAIN LOOP*************."
for process in list_of_processes:
    print "=========== Waiting for process: {} ===========".format(process.pid)
    process.wait()
            


# print "PYTHON SCRIPT DONE"