---
title: "LDSC: effect of including baseline annotations"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(plotly)
```


# Data
The analysis was done on BMI GWAS with the GTEx annotations.
`baseline` was run with `all_genes` and `baseline` as 'covariates'.
`no_baseline` was run with `all_genes` but NO `baseline`.



```{r}
df.baseline <- read_tsv("/raid5/projects/timshel/sc-genetics/ldsc/src/BMI1.GTEx.cell_type_results.txt")
df.no_baseline <- read_tsv("/raid5/projects/timshel/sc-genetics/ldsc/src/BMI1.GTEx_no_baseline.cell_type_results.txt")
```

```{r}
df.baseline
```

```{r}
df.no_baseline
```


# Wrangle data

```{r}
df <- full_join(df.baseline, df.no_baseline, by="Name", suffix=c(".baseline", ".no_baseline"))
```


# Plots

We see that the tau estimates tend to be bigger for the model with no baseline annotations.
```{r}
p <- ggplot(df, aes(x=Coefficient.baseline,y=Coefficient.no_baseline, dummy=Name)) + 
  geom_point() + 
  geom_abline() +
  labs(title="Tau estimates")
ggplotly(p)

```


```{r}
p <- ggplot(df, aes(x=Coefficient_P_value.baseline,y=Coefficient_P_value.no_baseline, dummy=Name)) + 
  geom_point() + 
  geom_abline() + 
  labs(title="P-values estimates")
ggplotly(p)


```


```{r}
p <- ggplot(df, aes(x=Coefficient_P_value.baseline,y=Coefficient_P_value.no_baseline, dummy=Name)) + 
  geom_point() + 
  geom_abline() + 
  scale_x_log10() + 
  scale_y_log10() + 
  labs(title="P-values estimates (log-scale)")
ggplotly(p)

```
