---
### YAML section (use # for comments)
title: "Sc-genetics: expr-export_avg_cell_type_expression"
author: "Pascal N. Timshel, Pers Lab"
date: "`r Sys.time()`" # Sys.Date()
output:
  html_notebook: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
  html_document:
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---


```{r, include=F}
# Here is the command to knit/render the notebook to HTML using commandline [requires pandoc installed on the system]
# Rscript -e 'library(rmarkdown); rmarkdown::render("/path/to/test.Rmd", "html_document")'
# Rscript -e 'library(rmarkdown); rmarkdown::render("/projects/timshel/sc-arc_lira/src/nb-poster_keystone/nb-poster_keystone.Rmd", "html_document")'
```


```{r global_options, include=FALSE}
knitr::opts_chunk$set(cache.lazy=FALSE, cache=FALSE)
```


# Introduction

1. READS FACS DATA
2. READS META DATA
3. LOADS INTO SEURAT

# Setup

Set working directory
```{r working_directory}
wd <- "/projects/timshel/maca/src/"
setwd(wd)
```


```{r load_libraries, warning=FALSE, message=FALSE, cache=FALSE}
library(Seurat)
library(tidyverse)
```


# Read expression data

```{r}
dir.data <- "/projects/timshel/maca/data/figshare/180126-facs/FACS"
files.data <- file.path(dir.data, list.files(dir.data, pattern="*.csv"))
files.data
```

```{r}
df.test <- read_csv("/projects/timshel/maca/data/figshare/180126-facs/FACS/Bladder-counts.csv", col_types=list(X1=col_skip())) # skips the gene names column. They are the same anyways.
```

## Read files

```{r}
### Reading files
list.dfs <- lapply(files.data, read_csv)

# ALTERNATIVE: skips the gene names column. They are all the same, and we do not want them for the bind_cols()
# list.dfs <- lapply(files.data, read_csv, col_types=list(X1=col_skip())) # skips the gene names column. They are all the same, and we do not want them for the bind_cols()

### IMPORTANT NOTE: all files have the SAME GENES IN THE SAME ORDER --> we can then use bind_cols() instead of join functions
# timshel@yggdrasil:/projects/timshel/maca/data/figshare/180126-facs/FACS> wc -l *
#      23434 Bladder-counts.csv
#      23434 Brain_Microglia-counts.csv
#      23434 Brain_Non-microglia-counts.csv
#      23434 Colon-counts.csv
#      23434 Fat-counts.csv
#      23434 Heart-counts.csv
#      23434 Kidney-counts.csv
#      23434 Liver-counts.csv
#      23434 Lung-counts.csv
#      23434 Mammary-counts.csv
#      23434 Marrow-counts.csv
#      23434 Muscle-counts.csv
#      23434 Pancreas-counts.csv
#      23434 Skin-counts.csv
#      23434 Spleen-counts.csv
#      23434 Thymus-counts.csv
#      23434 Tongue-counts.csv
#      23434 Trachea-counts.csv

```

```{r}
# save(list.dfs, file="list.dfs.RData")
# load(file="list.dfs.RData") # list.dfs
```


## Remove first column with gene names

```{r}
list.dfs.clean <- lapply(list.dfs, function(df) {df %>% select(-X1)}) # remove the "X1" column with the gene names
df.tmp.gene_names <- lapply(list.dfs, function(df) {df %>% select(X1)}) %>% bind_cols() # just for fun
```


## Bind columns and prepare for Seurat import

```{r}
df.expression <- list.dfs.clean %>% 
  bind_cols() %>% # bind_cols() binds via position
  as.data.frame() 
rownames(df.expression) <- list.dfs[[1]]$X1 # gene rownames. the rownames() are used by Seurat as gene names. 
```





# Read meta data: cell type annotations

```{r}
file.annotations <- "/projects/timshel/maca/data/figshare/180126-facs/annotations_FACS.csv"
df.annot <- read_csv(file.annotations)
```


```{r}
head(df.annot)
```


# Seurat: create object and normalize

```{r}
seurat_obj <- CreateSeuratObject(df.expression, min.cells = 3, min.genes = 200, is.expr = 0)
  # seurat takes as input a data frame or matrix.
  # the rownames() are used as gene names
  # the colnames()/names() are used as cell id

# seurat_obj@meta.data is 'born with' the meta data columns: "nGene", "nUMI", "orig.ident"
# we could change the name of nUMI to "total_expr"...
```

```{r}
seurat_obj <- NormalizeData(seurat_obj, normalization.method = "LogNormalize", scale.factor = 1e4)
```


# Add meta data to Seurat

```{r}
df.tmp.metadata <- data.frame(df.annot %>% select(-cell_ontology_term_iri, cell_ontology_id), row.names=df.annot$cell)
seurat_obj <- AddMetaData(seurat_obj, df.tmp.metadata)
str(seurat_obj@meta.data)
```

# EXPORT: save Seurat object

```{r}
save(seurat_obj, file="maca.seurat_obj.facs.figshare_180126.RData")
```



# TODO: make basic plots.
xxx
