---
title: "Compare LDSC results for different Espression Specificity (ES metrics)"
author: "Pascal N. Timshel, Pers Lab"
date: "`r Sys.time()`" # Sys.Date()
output:
  html_document:
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
  html_notebook: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---


```{r}
### Extract the code from the notebook
# knitr::purl("nb-template.Rmd", output = "output_code_blocks_extracted.R", documentation = 1)
```


# Setup

```{r, message = FALSE, results='hide', warning=FALSE}
library(tidyverse)
library(here)
library(GGally)

library(gghighlight)

source(here("src/lib/load_functions.R")) # load sc-genetics library
```



# Load data


```{r}
# ======================================================================= #
# =============================== LOAD LDSC CTS RESULTS ================================= #
# ======================================================================= #

### Mousebrain
# dataset_prefix <- "mousebrain_all"
# files.ldsc_cts <- c("raw"=here("out/out.ldsc/celltypes.mousebrain_raw_sems.all__BMI_Yengo2018.cell_type_results.txt"),
#                     "continuous"=here("out/out.ldsc/celltypes.mousebrain_cont.all__BMI_Yengo2018.cell_type_results.txt"),
#                     "binary"=here("out/out.ldsc/celltypes.mousebrain_binary.all__BMI_Yengo2018.cell_type_results.txt"))

### Tabula Muris
dataset_prefix <- "tabula_muris"
files.ldsc_cts <- c("raw"=here("out/out.ldsc/celltypes.tabula_muris_raw_sems.all__BMI_Yengo2018.cell_type_results.txt"),
                    "continuous"=here("out/out.ldsc/celltypes.tabula_muris_cont.all__BMI_Yengo2018.cell_type_results.txt"),
                    "binary"=here("out/out.ldsc/celltypes.tabula_muris_binary.all__BMI_Yengo2018.cell_type_results.txt"))

files.ldsc_cts
df.ldsc_cts <- bind_rows(lapply(files.ldsc_cts, load_ldsc_cts_results, dataset_prefix), .id="annotation_type")
df.ldsc_cts

### add annotation_type_sem
df.ldsc_cts <- df.ldsc_cts %>% mutate(annotation_type_sem = paste(annotation_type, sem, sep="__"))

```

# COMPARE BINARY TO CONTINUOUS


```{r}
# ======================================================================= #
# ====================== COMPARE BINARY TO CONTINUOUS =================== #
# ======================================================================= #

df.ldsc_cts.bin_vs_cont <- df.ldsc_cts %>% 
  filter(annotation_type %in% c("binary", "continuous")) %>% # no 'raw' included
  mutate(p.value.mlog10 = -log10(p.value)) %>%
  select(sem, p.value.mlog10, annotation, annotation_type) %>% # need to remove all columns with 'SEM unique' values before calling spread()
  spread(key=annotation_type, value=p.value.mlog10)

df.ldsc_cts.bin_vs_cont
```



```{r}
### Plot
ggplot(df.ldsc_cts.bin_vs_cont, aes(binary, continuous)) + 
  geom_point() + 
  geom_abline() + 
  ggpubr::stat_cor(method = "pearson") +
  labs(title=sprintf("%s - binary vs continuous", dataset_prefix))
```


# COMPARE individual SEMS RESULTS

```{r, fig.height=12, fig.width=12}
# ======================================================================= #
# ====================== COMPARE individual SEMS RESULTS =================== #
# ======================================================================= #
# FYI: you can do the comparison of individual SEM results for both binary, continuous and raw.

for (tmp_filter in c("continuous", "binary", "raw")) {
  df.ldsc_cts.spread <- df.ldsc_cts %>% 
    filter(annotation_type==tmp_filter) %>%  # SWTICH
    mutate(p.value.mlog10 = -log10(p.value)) %>%
    select(sem, p.value.mlog10, annotation) %>% # need to remove all columns with 'SEM unique' values before calling spread()
    spread(key=sem, value=p.value.mlog10)
  # df.ldsc_cts.spread
  p <- GGally::ggpairs(df.ldsc_cts.spread %>% select(-annotation), # ALT: columns=c("ges", "sem_mean", "si", "specificity", "tstat")
                       title=tmp_filter,
                       progress=FALSE)
  print(p)
}
```


# COMPARE RAW TO CONTINUOUS

```{r}
# ======================================================================= #
# ====================== COMPARE RAW (cont) TO CONT (cont) =================== #
# ======================================================================= #

df.ldsc_cts.spread <- df.ldsc_cts %>% 
  filter(annotation_type %in% c("continuous", "raw")) %>% 
  mutate(p.value.mlog10 = -log10(p.value)) %>%
  select(sem, p.value.mlog10, annotation, annotation_type) %>% 
  spread(key=annotation_type, value=p.value.mlog10) %>% 
  filter(complete.cases(.)) # remove SEMs that were not computed for both raw and continuous. ALT: drop_na. 

df.ldsc_cts.spread
```


```{r, fig.height=12, fig.width=12}

p <- ggplot(df.ldsc_cts.spread, aes(x=continuous, y=raw)) + 
  geom_point() +
  gghighlight((raw > 2), max_highlight = 4L, label_key = annotation) +
  geom_abline() +
  facet_wrap(~sem)
p
```

# Compare sem_mean to Skene and Finucane

```{r}
df.ldsc_cts.spread <- df.ldsc_cts %>% 
  filter(annotation_type_sem %in% c("continuous__sem_mean", "raw__specificity_top10pct_binary", "raw__tstat_top10pct_binary")) %>% 
  mutate(p.value.mlog10 = -log10(p.value)) %>%
  select(p.value.mlog10, annotation, annotation_type_sem) %>% 
  spread(key=annotation_type_sem, value=p.value.mlog10)
head(df.ldsc_cts.spread)
```


```{r, fig.height=10, fig.width=10}
# Skene
p <- ggplot(df.ldsc_cts.spread, aes(x=continuous__sem_mean, y=raw__specificity_top10pct_binary)) + 
  geom_point() +
  gghighlight((continuous__sem_mean > 2), max_highlight = 4L, label_key = annotation) +
  geom_abline()
p

# Finucane
p <- ggplot(df.ldsc_cts.spread, aes(x=continuous__sem_mean, y=raw__tstat_top10pct_binary)) + 
  geom_point() +
  gghighlight((continuous__sem_mean > 2), max_highlight = 4L, label_key = annotation) +
  geom_abline()
p 

```

# Export 

```{r}
### format
df.ldsc_cts.export <- df.ldsc_cts %>% select(annotation_type_sem, p.value, annotation) %>% spread(key=annotation_type_sem, value=p.value) # format file

### add metadata
df.metadata <- get_metadata(dataset_prefix)
df.ldsc_cts <- df.ldsc_cts %>% left_join(df.metadata, by="annotation") # add meta data
df.ldsc_cts.export <- df.ldsc_cts.export %>% left_join(df.metadata, by="annotation") # add meta data

### export
df.ldsc_cts.export %>% write_csv(sprintf("out.tmp.190129.%s.ES_COMPARISON.BMI_Yengo2018.csv", dataset_prefix))
```



```{r}
# ======================================================================= #
# ================================ PLOT: cell priori [MULTI-GWAS] ================================= #
# ======================================================================= #

list.dfs.split <- split(df.ldsc_cts, df.ldsc_cts$annotation_type_sem)
names(list.dfs.split)

for (name_elem in names(list.dfs.split)) {
  print(name_elem)
  df.plot <- list.dfs.split[[name_elem]]

  fdr_threshold <- 0.05/nrow(df.plot)
  p <- ggplot(df.plot, aes(x=annotation, y=-log10(p.value))) +
    geom_point(aes(color=color_by_variable, size=estimate)) +
    ggrepel::geom_text_repel(data=df.plot %>% filter(fdr_significant), aes(x=annotation, y=-log10(p.value), label=annotation, color=color_by_variable), hjust = 0, nudge_x = 1.5) + # OBS geom_text_repel
    geom_hline(yintercept=-log10(fdr_threshold), color="red") +
    labs(x="Cell Type", y="-log10(P-value)") + # expression(-log[10]("P-value"))
    ggtitle(sprintf("BMI_Yengo2018 | %s - %s", dataset_prefix, name_elem)) +
    theme_classic() +
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank())
  file.out <- sprintf("out.tmp.190129.plot.cell_prioritization.%s.%s.color_by_class.pdf", dataset_prefix, name_elem)
  ggsave(p, filename=file.out, width=20, height=8)
}

```

