---
title: "LDSC: h2 models"
output: html_notebook
---
  
```{r}
library(tidyverse)
library(ggplot2)
library(plotly)

library(GGally)
```


# Data

```{r}
df <- read_tsv("/projects/timshel/sc-genetics/sc-genetics/src/ldsc/experiments/experiment.gtex_tissues.h2.ALL_MODELS.BMI_Yengo2018.txt")
```

```{r}
df
```



# Wrangle data

```{r}
df.gather <- df %>% select(Model, Annotation, Enrichment, Enrichment_p, `Coefficient_z-score`) %>% gather(key="key", value="value", -Model,-Annotation)
head(df.gather)
```


## Enrichment
```{r, fig.height=16, fig.width=16}
df.pairs <- df %>% select(Model, Annotation,Enrichment) %>% spread(Model, Enrichment)
ggpairs(df.pairs %>% select(-Annotation))
```


## Enrichment_p
```{r, fig.height=16, fig.width=16}
df.pairs <- df %>% select(Model, Annotation,Enrichment_p) %>% spread(Model, Enrichment_p)
ggpairs(-log10(df.pairs %>% select(-Annotation))) # -log10
```

## Coefficient_z-score (ala -log10(tau_pvalue))
```{r, fig.height=16, fig.width=16}
df.pairs <- df %>% select(Model, Annotation,`Coefficient_z-score`) %>% spread(Model,`Coefficient_z-score`)
ggpairs(df.pairs %>% select(-Annotation)) # this is basically the  -log10(tau_pvalue)
```


